# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

armaMatMult <- function(A, B) {
    .Call(`_test_armaMatMult`, A, B)
}

eigenMatTrans <- function(A) {
    .Call(`_test_eigenMatTrans`, A)
}

eigenMatMult <- function(A, B) {
    .Call(`_test_eigenMatMult`, A, B)
}

eigenMapMatMult <- function(A, B) {
    .Call(`_test_eigenMapMatMult`, A, B)
}

rcpp_hello_world <- function() {
    .Call(`_test_rcpp_hello_world`)
}

